# Generated by Django 4.1 on 2024-01-13 21:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("task_manager", "0003_alter_task_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="worker",
            options={
                "ordering": ["position__name", "first_name", "last_name"],
                "verbose_name": "user",
            },
        ),
    ]
